module.exports = {
  COMMUNITY_CHAT: 'COMMUNITY_CHAT',
  USER_VERIFY: 'VERIFY_USER',
  USER_CONNECTED: 'USER_CONNECTED',
  USER_DISCONNECTED: 'USER_DISCONNECTED',
	MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
	MESSAGE_SENT: 'MESSAGE_SENT',
	TYPING: 'TYPING',
	LOGOUT: 'LOGOUT'
}
